---
- name: Enforce Password Policies in Ubuntu / Debian
  community.general.pamd:
    name: common-password
    type: password
    control: requisite
    module_path: pam_pwquality.so
    module_arguments: "{{ module_arguments }}"
    state: args_present
  when:
    - ansible_facts['os_family'] == "Debian"

- name: Enforce Password Policies in CentOS / RHEL
  community.general.pamd:
    name: system-auth
    type: password
    control: requisite
    module_path: pam_pwquality.so
    module_arguments: "{{ module_arguments }}"
    state: args_present
  when:
    - ansible_facts['os_family'] == "RedHat"